### ISSUE TITLE
Test buzzer with PWM0 and PWM1

### ISSUE THREAD

**Issue by davidperrenoud** [davidperrenoud/Gamegirl#2]

**Comment by davidperrenoud** [comment]
Tested both left (PWM1) and right (PWM0) channels with a transistor + buzzer and it works, although not very loud and of low quality.

@Kivutar Do we need stereo?

**Comment by kivutar** [comment]
We can downmix to 1 channel on the alsa side https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=33431

**Comment by davidperrenoud** [comment]
It works! I had to modify ~/.asoundrc (because /etc/asound.conf was being overridden by ~/.asoundrc)
